import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Layout, Menu, Button, Row, Col, Card, Input } from "antd";
import { SearchOutlined } from "@ant-design/icons";

const { Header, Footer } = Layout;
const { Search } = Input;

export default function Home() {
  const onSearch = (value) => console.log(value);

  return (
    <div className={styles.container}>
      <Head>
        <title>Mononton</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header className={styles.header}>
        <h1 className={styles.logo}>Mononton</h1>
        <Menu mode="horizontal">
          <Menu.Item key="Movie">{`Movie`}</Menu.Item>
          <Menu.Item key="Series">{`Series`}</Menu.Item>
          <Menu.Item key="Popular Actors">
            <Button>Popular Actors</Button>
          </Menu.Item>
        </Menu>
      </Header>
      <main>
        <div className={styles.jumbotron}>
          <img src="/images/banner.png" alt="banner" width="100%" />
          <h1>Cari Film Favorit Kamu di Mononton!</h1>
        </div>
        <div className={styles.card}>
          <Row gutter={[16, 16]}>
            <Col md={20}>
              <Input placeholder="Cari Film Favorit Kamu Disini ..." />
            </Col>
            <Col md={4} className="text-center">
              <Button type="primary">
                <SearchOutlined className={styles.icon} />
              </Button>
            </Col>
          </Row>
        </div>
        <div>
          <Row gutter={[64, 32]}>
            <Col md={24}>
              <h1 className="text-center font-bold">Film Populer Hari Ini</h1>
            </Col>
            <Col md={8}>
              <div className={styles.movieCard}>
                <img src="/images/movie-1.png" alt="banner" width="100%" />
                <p>Squid Games</p>
                <Row>
                  <Col md={12}>
                    <span className={styles.rating}>8.0 Ratings</span>
                  </Col>
                  <Col md={12} className="text-right">
                    <span className={styles.date}>Sep 17, 2021</span>
                  </Col>
                </Row>
              </div>
            </Col>
            <Col md={8}>
              <div className={`${styles.movieCard} ${styles.movieCardActive}`}>
                <img src="/images/movie-1.png" alt="banner" width="100%" />
                <p>Squid Games</p>
                <Row>
                  <Col md={12}>
                    <span className={styles.rating}>8.0 Ratings</span>
                  </Col>
                  <Col md={12} className="text-right">
                    <span className={styles.date}>Sep 17, 2021</span>
                  </Col>
                </Row>
              </div>
            </Col>
            <Col md={8}>
              <div className={styles.movieCard}>
                <img src="/images/movie-1.png" alt="banner" width="100%" />
                <p>Squid Games</p>
                <Row>
                  <Col md={12}>
                    <span className={styles.rating}>8.0 Ratings</span>
                  </Col>
                  <Col md={12} className="text-right">
                    <span className={styles.date}>Sep 17, 2021</span>
                  </Col>
                </Row>
              </div>
            </Col>
          </Row>
        </div>
      </main>
      <Footer style={{ textAlign: "center" }}>Created By Kelompok 3</Footer>
    </div>
  );
}
